steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deployMyFunction'
    args: ['functions', 'deploy','get-url-content', '--source' , 'functions/get-url-content', '--runtime' , 'python37' ,'--trigger-http']